<?php
namespace App\Http\Controllers\Admin\Role;
use App\Models\Permission;
use App\Renders\Form;
use App\Renders\Grid;
use App\Http\Controllers\Admin\Common\BasePage;
use App\Http\Controllers\Admin\Common\Css;
use App\Models\Role;
use App\Renders\Facades\SectionContent;
use App\Renders\Layout\Content;
use App\Renders\Widgets\Box;
use Illuminate\Support\Facades\Input;

class Page extends BasePage
{
    public function __construct()
    {
        $this->setBoxTitle('角色管理');
        parent::__construct();
    }

    protected function buildGrid(Grid $grid)
    {
        $grid->id('ID')->sortable();
        $grid->name('标识');
        $grid->display_name('名称');
        $grid->permissions('权限')->display(function ($permissions){
            $permissionStr = '';
            if($permissions){
                foreach ($permissions as $permission){
                    $permissionStr .= "<span class='label label-success'>{$permission['display_name']}</span>";
                }
                return $permissionStr;
            }else{
                return "<span class='label label-default'>未获得权限</span>";
            }

        });
        $grid->with(['id' => 'role-table']);
        return parent::buildGrid($grid); // TODO: Change the autogenerated stub
    }

    protected function buildForm(Form $form, $id = null): BasePage
    {
        if($id){
            $form->display('id', 'ID');
        }
        $form->text('name', '标识')->rules('required');
        $form->text('display_name', '名称');
        $form->textarea('description', '描述');
        $form->listbox('permissions', trans('admin.permissions'))
            ->options(Permission::doesntHave('menu')->where('name', '!=', Permission::ALL_RIGHT)->pluck('display_name', 'id'))
            ->settings([
                "nonSelectedListLabel" => '已有角色',
                "selectedListLabel" => '未有角色',
                "preserveSelectionOnMove" => 'moved',
                "moveOnSelect" => false, //出现一个剪头，表示可以一次选择一个
                "filterTextClear" => '展示所有',
                "moveSelectedLabel" => "添加",
                "moveAllLabel" => '添加所有',
                "removeSelectedLabel" => "移除",
                "removeAllLabel" => '移除所有',
                "infoText" => '共{0}个',
            ]);
        return parent::buildForm($form, $id); // TODO: Change the autogenerated stub
    }
}