<?php
namespace App\Http\Controllers\Admin\Order;

use App\Models\Order;

class Grid extends \App\Renders\Grid
{
    protected $view = 'store.order.grid.table';

    protected $orderNo = '';

    protected $colors = [];

    public function build()
    {
        if ($this->builded) {
            return;
        }
        $this->model()->with(['orderItems.user', 'orderItems.refund']);
        $data = $this->processFilter();
        $this->prependRowSelectorColumn();
        $this->appendActionsColumn();


        $this->buildRows($data);

        $this->builded = true;
    }

    protected function buildRows(array $data)
    {
        collect($data)->map(function ($model, $number) {
            $this->rows->push(new Row($number, $model));
        });

        if ($this->rowsCallback) {
            $this->rows->map($this->rowsCallback);
        }
    }

    public function render()
    {
        $this->variables['id'] = str_random();
        return parent::render(); // TODO: Change the autogenerated stub
    }
}