<?php

namespace App\Notifications\Wechat;

use App\Channels\Messages\WechatTemplateMessage;
use App\Models\User;
use Illuminate\Bus\Queueable;
use App\Notifications\Wechat\TemplateMessageSender as Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notifiable;

class CommissionSettlement extends Notification
{

    protected $templateMessageId = null;


    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
        $this->templateMessageId = config('wechat.message_template.commission_settlement');
        parent::__construct();
    }


    /**
     * @param Notifiable $notifiable
     * @param string $driver
     * @return WechatTemplateMessage
     * @throws
     * */
    public function toWxMsgTemplate(Notifiable $notifiable, string  $driver = 'wechat')
    {
        //模版消息设置代码写在这里
        if(isset($notifiable->miniProgramUser) && isset($notifiable->miniProgramUser->open_id)){
            $this->templateMessage
                ->setTemplateId($this->templateMessageId)
                ->setTo($notifiable->miniProgramUser->open_id)
                ->setMessageData([]);
            return parent::toWxMsgTemplate($notifiable); // TODO: Change the autogenerated stub
        }else{
            throw new \Exception('没有微信open id');
        }
    }
}
