<?php
namespace App\Renders\From\Field;

class VueUpload extends File
{
    public function getView()
    {
        return 'components.form.vue-upload'; // TODO: Change the autogenerated stub
    }

    public function setUrl($url)
    {
        $this->attributes['url'] = $url;
    }
}