<?php
namespace App\Renders\From\Field;

class VueUpload extends File
{

    public function prepare($string)
    {
        return $string;
    }

    public function append($string)
    {
        if (is_null($this->append)) {
            $this->append = $string;
        }

        return $this;
    }

    public function getView()
    {
        return 'components.form.vue-upload'; // TODO: Change the autogenerated stub
    }

    public function setUrl($url)
    {
        $this->attributes['url'] = $url;
    }
}