<?php
namespace App\Http\Controllers\Admin\Setting;

use App\Http\Controllers\Admin\Common\BasePage;
use App\Renders\Facades\SectionContent;
use App\Renders\Form;
use App\Renders\From\Row;
use App\Renders\Layout\Content;
use App\Renders\Widgets\Box;

class Page extends BasePage
{
    public function __construct()
    {
        parent::__construct();
        $this->setBoxTitle('管理员信息设置');
    }

    public function buildForm(Form $form, $id = null): BasePage
    {
        $css = <<<CSS
input{
    opacity: inherit !important;
}
CSS;

        SectionContent::css($css);
        $id = \Auth::id();
        $form->setAction("/user/{$id}/edit");
        $form->vueUpload('head_image_url', '头像')->attribute(['url' => '/ajax/user/avatar', 'id' => 'app', 'xthumb' => \Auth::user()->head_image_url]);
        $form->display('mobile', '手机')->readOnly();
        $form->text('nickname', '昵称');
        $form->radio('sex', '性别')->options([
            'MALE' => '男',
            'FEMALE' => '女'
        ]);
        return parent::buildForm($form, $id); // TODO: Change the autogenerated stub
    }
}