<?php
namespace App\Renders\Widgets\BootstrapTable;
use App\Renders\Widgets\Widget;

class Toolbar extends Widget
{
    /**
     *@var Widget[]   $childrenWidgets
     * */
    protected $childrenWidgets = [];
    public function __construct($attributes = [])
    {
        parent::__construct($attributes);
    }

    public function render()
    {
        // TODO: Implement render() method.
    }

    /**
     *
     * */
    protected function template(): string
    {
        // TODO: Change the autogenerated stub
        $elements = "";
        foreach ($this->childrenWidgets as $widget){
            $elements .= $widget->render();
        }
        return <<<TOOLBA
            <div {$this->formatAttributes()}>
                {$elements}
            </div>
TOOLBA;
    }
}