<?php
namespace App\Http\Controllers\Admin\Menu;

use App\Http\Controllers\Admin\Common\BasePage;
use App\Renders\Form;
use App\Renders\Grid;
use App\Renders\Tree;
use App\Renders\Widgets\Tab;

class Page extends BasePage
{
    public function __construct()
    {
        $this->setBoxTitle('菜单管理');
        parent::__construct();
    }

    protected function buildForm(Form $form, $id = null): BasePage
    {
        return parent::buildForm($form, $id); // TODO: Change the autogenerated stub
    }

    protected function buildGrid(Grid $grid)
    {
        $grid->id('ID')->sortable();
        $grid->text('标题');
        $grid->icon('图标')->display(function ($value){
            return "<i class=\"fa fa-fw fa-{$value} \"></i>";
        });
        $grid->column('permission.display_name', '权限');
        $grid->column('permission.roles', '授权角色')->display(function ($roles){
            $roleStr = '';
            if($roles){
                foreach ($roles as $role){
                    $roleStr .= "<span class='badge badge-success'>{$role['display_name']}</span>";
                }
                return $roleStr;
            }else{
                return "<span class='badge badge-warning'>未开放</span>";
            }

        });
        $grid->with(['id' => 'menu-table']);
        return parent::buildGrid($grid); // TODO: Change the autogenerated stub
    }

    public function buildTab(Tab $tab): BasePage
    {
        $tab->add('菜单表单',$this->grid(), true)->add('菜单结构', $this->tree());
        return parent::buildTab($tab); // TODO: Change the autogenerated stub
    }

    public function buildTree(Tree $tree)
    {
        $tree->disableCreate();

        $tree->branch(function ($branch) {
            $payload = "<i class='fa {$branch['icon']}'></i>&nbsp;<strong>{$branch['text']}</strong>";

            if (!isset($branch['children'])) {
                if (url()->isValidUrl($branch['url'])) {
                    $url = $branch['url'];
                } else {
                    $url = admin_base_path($branch['url']);
                }

                $payload .= "&nbsp;&nbsp;&nbsp;<a href=\"$url\" class=\"dd-nodrag\">$url</a>";
            }

            return $payload;
        });
        return parent::buildTree($tree); // TODO: Change the autogenerated stub
    }
}