<?php
namespace App\Http\Controllers\Admin\Merchandise;
use App\Http\Controllers\Admin\Common\BasePage;
use App\Models\Category;
use App\Models\Merchandise;
use App\Renders\Facades\SectionContent;
use App\Renders\Grid;

class Page extends BasePage
{
    public function __construct()
    {
        $this->setBoxTitle('商品管理');
        parent::__construct();
    }

    protected function filter(Grid\Filter $filter)
    {
        $filter->like('store.name', '店铺名称');
        $filter->like('code', '商品编号');
        $filter->like('name', '商品名称');
        $filter->equal('status', '商品状态')->select(Merchandise::STATUS_ZH_CN);
        $filter->between('prime_price', '商品价格')->currency([
            'min' => 0.00,
            'step' => 0.01
        ]);
        $filter->between('stock_num', '商品库存')->integer();
        $filter->equal('category_id', '商品分类')->select(Category::all()->pluck('name', 'id'));
        parent::filter($filter); // TODO: Change the autogenerated stub
    }

    protected function buildGrid(Grid $grid)
    {
        $css = <<<CSS
.goods-info-float {
    float: left;
    padding-left: 5px;
    text-align: left;
}
CSS;
        SectionContent::css($css);
        $grid->id('ID')->sortable();
        $grid->code('商品编号');
        $grid->column('main_image_url', '商品信息')->display(function ($image, $merchandise){
            return <<<HTML
            <div class="goods-info-float">
                <img src="{$image}" style="height:50px;width:80px">
            </div>
            <div class="goods-info-float" style="margin-top: 10px;">
                {$merchandise['name']}
            </div>
HTML;
        });
        $grid->column('store.name', '店铺名称');
        $grid->column('category.name', '分类名称');
        $grid->prime_price('单价')->sortable();
        $grid->stock_num('库存')->sortable();
        $grid->sell_num('销量')->sortable();
        $grid->status('状态')->display(function ($value) {
            $status = Merchandise::STATUS_ZH_CN[$value];
            switch ($value){
                case Merchandise::STATUS['TAKEN_OFF']:{
                    return <<<STATUS
<span class = "label label-default">{$status}</span>
STATUS;
                    break;
                }
                case Merchandise::STATUS['ON_SHELVES']:{
                    return <<<STATUS
<span class = "label label-success" >{$status}</span>
STATUS;
                    break;
                }
                case Merchandise::STATUS['SELL_OUT']:{
                    return <<<STATUS
<span class = "label label-warning">{$status}</span>
STATUS;
                    break;
                }
            }

        });
        $grid->sort('序号')->sortable();
        $grid->created_at('创建时间');
        return parent::buildGrid($grid); // TODO: Change the autogenerated stub
    }
}